---
actions:
  to: kubernetes/overlays/dev/cd/resources/dev/service.yaml
---

kind: Service
apiVersion: apps/v1
metadata:
  name: service
spec:
  # type: LoadBalancer
  sessionAffinity: None
  ports:
    - port: 80
      targetPort: 8080