---
actions:
  to: kubernetes/overlays/dev/image.yaml
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: spring-petclinic
  # namespace: cf-workloads-staging
spec:
  tag: harbor.tanzudemo.frankcarta.com/spring-petclinic/spring-petclinic
  imageTaggingStrategy: BuildNumber
  failedBuildHistoryLimit: 10
  successBuildHistoryLimit: 10
  cacheSize: 2G
  # serviceAccount: cc-kpack-registry-service-account
  builder:
    kind: ClusterBuilder
    name: base
  source:
    git:
      url: https://github.com/samarsinghal/spring-petclinic.git
      revision: main