---
actions:
  to: kubernetes/overlays/dev/ci/trigger-template.yaml
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy-template
  namespace: tekton-pipelines
spec:
  params:
  - name: imageDigest
    description: The Image Digest
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-
    spec:
      pipelineRef:
        name: build-deploy
      serviceAccountName: pipeline
      params:
      - name: imageDigest
        value: $(tt.params.imageDigest)
      - name: argo-app-name
        value: {{artifactId}}
      - name: configGitUrl
        value: 'git@github.com:samarsinghal/{{artifactId}}.git'
      - name: appImage
        value: 'harbor.tanzudemo.frankcarta.com/{{artifactId}}/{{artifactId}}'
      workspaces:
      - name: config-source
        emptyDir: {}
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-deploy-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: imageDigest
    value: $(body.event_data.resources[0].digest)
---
