# ---
# actions:
#   to: kubernetes/overlays/dev/cd/resources/kustomization.yaml
# ---

# namePrefix: {{artifactId}}-
# commonLabels:
#   app.kubernetes.io/name: {{artifactId}}
# images:
#   - name: repository-project/application:1.0.0  #used for Kustomize matching
#     newName: harbor.tanzudemo.frankcarta.com/{{artifactId}}/{{artifactId}}
#     newTag: latest
# configMapGenerator:
#   - name: spring-configmap  # naming convention in base use to mount the file to /config/application.properties in a persistent volume
#     files:
#       - ../../application/application.properties
#   - name: spring-configmap-env  # naming convention in base to load environment variables from a reference to this config map
#     envs:
#       - ../../application/env.properties
# resources:
#   - dev/deployment.yaml
#   - dev/service.yaml

# # patches:
# # - ../../application/deployment-patch.yaml
