---
actions:
  to: kubernetes/overlays/dev/cd/resources/kustomization.yaml
---

namePrefix: spring-petclinic-
commonLabels:
  app.kubernetes.io/name: spring-petclinic
images:
  - name: repository-project/application:1.0.0  #used for Kustomize matching
    newName: samarsinghal/{{artifactId}}
    newTag: latest
configMapGenerator:
  - name: spring-configmap  # naming convention in base use to mount the file to /config/application.properties in a persistent volume
    files:
      - ../../application/application.properties
  - name: spring-configmap-env  # naming convention in base to load environment variables from a reference to this config map
    envs:
      - ../../application/env.properties
resources:
  - github.com/samarsinghal/spring-boot-web

patches:
- ../../application/deployment-patch.yaml
